project:
  type: website

website:
  title: "Gerard Rocher-Ros"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - publications.qmd
      - projects.qmd
      - softwares.qmd
      - science_society.qmd
      - about.qmd
      

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true

editor: source

